name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      # It is necessary to check that the package builds without errors
      - name: Build package
        run: npm run build
      # And that all tests pass successfully
      - name: Run tests
        run: npm test
